a= int(input('перше число x:'))
b= int(input('друге число x:'))
x= int(input('Ще одне число y:'))
y= int(input('Також друге число y:'))
c= int(str(a)+str(b))
d= int(str(x)+str(y))
print('Відповідь:','x=',c,'y=',d)
